#This will be where you put your secret key. This is an added layer of security in order to prevent others from logging
#into your server via their own methods. Put it here and do not share it with others. You can make it whatever you want.
secret = "SecretKeyHere"