#WARNING! This plugin does not offer compatibility for other worlds besides the normal vanilla overworld!
#Changes made to the server's normal world functionality will break this plugin! Compatibility will be coming in the future
#Permission list for the transfer command:
# transferclient.transfer.register
# transferclient.transfer.listservers
# transferclient.transfer.remserver
# transferclient.transfer.showcoord
# transferclient.transfer.remcoord
# transferclient.transfer.test
# transferclient.transfer.setspawn
# transferclient.transfer.toggleforcedspawn
# transferclient.transfer.editmode

#Forces the player to spawn at the same specified spawn point on every login.
forcedspawn: false
#The spawn point for forced spawn. The format is x-y-z and is in whole numbers
spawn: 0 4 0
#This will be where you put your secret key. This is an added layer of security in order to prevent others from logging
#into your server via their own methods. Put it here and do not share it with others. You can make it whatever you want.
#You only need this if you're not using the MODERN velocity protocol
secret: 'SecretKeyHere'